**Wine Quality Predicition**

Objective :
The objective of the Project is to predict the quality of the wine using Wine.

DATA SOURCE :THE DATA OF THE WINES (DATA SET) IS TAKEN FROM THE GITHUB ACCOUNT OF YBI FOUNDATION ,IN THE RAW FORMAT.

**IMPORT** **LIBRARY**

In [1]:
import pandas as pd

In [12]:
import numpy as np

**IMPORT** **DATA**

In [26]:
df=pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/WhiteWineQuality.csv',sep=';')

**Describe** **Data**

In [15]:
df.describe()

fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
count                                                4898                                                                                                                     
unique                                               3961                                                                                                                     
top     7.3;0.19;0.27;13.9;0.057;45;155;0.99807;2.94;0...                                                                                                                     
freq                                                    8

**Data** **Visualization**

In [16]:
df.head()

fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0   7;0.27;0.36;20.7;0.045;45;170;1.001;3;0.45;8.8;6                                                                                                                     
1  6.3;0.3;0.34;1.6;0.049;14;132;0.994;3.3;0.49;9...                                                                                                                     
2  8.1;0.28;0.4;6.9;0.05;30;97;0.9951;3.26;0.44;1...                                                                                                                     
3  7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4...                                                                                                                     
4  7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4...

**DATA** **PREPROCESSING**

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 1 columns):
 #   Column                                                                                                                                                                   Non-Null Count  Dtype 
---  ------                                                                                                                                                                   --------------  ----- 
 0   fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"  4898 non-null   object
dtypes: object(1)
memory usage: 38.4+ KB


In [18]:
df.columns

Index(['fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"'], dtype='object')

**Define Target Variable (y) and Feature Variables (X)**

In [27]:
y=df['quality']

In [28]:
y.shape

(4898,)

In [29]:
y


0       6
1       6
2       6
3       6
4       6
       ..
4893    6
4894    5
4895    6
4896    7
4897    6
Name: quality, Length: 4898, dtype: int64

In [31]:
X=df[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates',
      'alcohol']]

In [32]:
X=df.drop(['quality'],axis=1)

**TRAIN_TEST_SPLIT**

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,stratify=y,random_state=2529)

In [35]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((3428, 11), (1470, 11), (3428,), (1470,))

**MODELING**

In [36]:
from sklearn.svm import SVC

In [37]:
svc=SVC()

In [38]:
svc.fit(X_train,y_train)

SVC()

**MODEL** **PREDICATION**

In [40]:
y_pred=svc.predict(X_test)

In [41]:
y_pred.shape


(1470,)

In [42]:
y_pred

array([6, 6, 6, ..., 6, 6, 6])

**MODEL** **EVALUATION**

In [43]:
from sklearn.metrics import confusion_matrix,classification_report

In [44]:
print(confusion_matrix(y_test,y_pred))

[[  0   0   1   5   0   0   0]
 [  0   0   0  49   0   0   0]
 [  0   0  10 427   0   0   0]
 [  0   0  11 649   0   0   0]
 [  0   0   0 264   0   0   0]
 [  0   0   0  53   0   0   0]
 [  0   0   0   1   0   0   0]]


In [45]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         6
           4       0.00      0.00      0.00        49
           5       0.45      0.02      0.04       437
           6       0.45      0.98      0.62       660
           7       0.00      0.00      0.00       264
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00         1

    accuracy                           0.45      1470
   macro avg       0.13      0.14      0.09      1470
weighted avg       0.34      0.45      0.29      1470



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**EXPLAINATION:**
HERE WE CREATED A PROJECT OF WHITE WINE PREDICATION WSING ML FOR THIS PROJECT THE RESOURCE OF THE DATA IS THE DATASET GIVEN IN THE GITHUB ACCOUNT OF THE YBI FOUNDATION ,WE ALSO USED THE PANDAS LIBARAY ,SKLEARN LIBARAY FOR USING THE THINGS LIKE THE TRAIN_TEST_SPLIT ETC

THE QUICK STEPS ARE
IMPORT PYTHON LIBARIRES

IMPORT THE DATASETS

DISPLAY SOME DATA FROM THE DATASET IE THE HEAD ,INFO ,DESCRIBE,COLMNS ETC

DECLARE THE y AND X VARIABLES WHERE THE Y IS INDEPENDENT VARIABLE WHERE AS THE X IS A DEPENDENT VARIABLE

NOW USE SKLEARN MODEL FOR TRAIN_TEST_SPLIT

NOW PREDICT THE MODEL

NOW EVALUATE THE MODEL


